/* SAT Word Blitz — original concise definitions for gameplay.
   Not copied from commercial prep books. */
window.SAT_WORDS = [
  { w: "abate", d: "to lessen in force or intensity" },
  { w: "abdicate", d: "to give up a throne, office, or duty" },
  { w: "aberration", d: "a departure from what is normal or expected" },
  { w: "abhor", d: "to regard with intense dislike" },
  { w: "abject", d: "utterly hopeless, wretched, or degrading" },
  { w: "abridge", d: "to shorten by condensing while keeping the sense" },
  { w: "abscond", d: "to leave secretly to avoid capture or duty" },
  { w: "abstruse", d: "difficult to understand; obscure" },
  { w: "accolade", d: "an expression of high praise or honor" },
  { w: "acrimony", d: "bitter sharpness of speech or feeling" },
  { w: "adroit", d: "skillful and clever with hands or mind" },
  { w: "adulation", d: "excessive admiration or flattery" },
  { w: "adversity", d: "hardship or misfortune" },
  { w: "aesthetic", d: "concerned with beauty or artistic taste" },
  { w: "affable", d: "friendly and easy to talk to" },
  { w: "alacrity", d: "cheerful eagerness and promptness" },
  { w: "alleviate", d: "to make pain or a problem less severe" },
  { w: "aloof", d: "emotionally distant or uninvolved" },
  { w: "altruistic", d: "showing unselfish concern for others" },
  { w: "ambiguous", d: "open to more than one interpretation" },
  { w: "ambivalent", d: "having mixed or conflicting feelings" },
  { w: "ameliorate", d: "to make a situation better or more tolerable" },
  { w: "amiable", d: "good-natured and likable" },
  { w: "amorphous", d: "lacking a definite shape or structure" },
  { w: "anachronism", d: "something placed outside its proper time" },
  { w: "analogous", d: "comparable in a way that suggests a likeness" },
  { w: "anecdote", d: "a short, revealing personal story" },
  { w: "anomaly", d: "something that breaks the usual pattern" },
  { w: "antagonist", d: "a person who opposes or competes with another" },
  { w: "antipathy", d: "a deep-seated dislike" },
  { w: "apathetic", d: "showing little interest, energy, or emotion" },
  { w: "apocryphal", d: "of doubtful authenticity; probably untrue" },
  { w: "arbitrary", d: "based on random choice rather than reason" },
  { w: "archaic", d: "belonging to an earlier, outdated period" },
  { w: "arduous", d: "requiring great effort; strenuous" },
  { w: "articulate", d: "able to express ideas clearly and effectively" },
  { w: "ascetic", d: "practicing severe self-discipline and abstinence" },
  { w: "assiduous", d: "showing persistent, careful effort" },
  { w: "astute", d: "shrewdly perceptive and clever" },
  { w: "atrophy", d: "to waste away from lack of use" },
  { w: "audacious", d: "boldly daring, often to the point of recklessness" },
  { w: "austere", d: "severely plain or sternly self-disciplined" },
  { w: "autonomous", d: "independent and self-governing" },
  { w: "avarice", d: "extreme greed for wealth" },
  { w: "banal", d: "so commonplace as to be dull" },
  { w: "belittle", d: "to make someone or something seem unimportant" },
  { w: "belligerent", d: "hostile and eager to fight" },
  { w: "benevolent", d: "kindly and well-meaning" },
  { w: "benign", d: "gentle and harmless" },
  { w: "bequeath", d: "to leave property to someone by a will" },
  { w: "bolster", d: "to support, prop up, or strengthen" },
  { w: "bombastic", d: "pompous in speech but thin in meaning" },
  { w: "brevity", d: "concise shortness of expression" },
  { w: "bucolic", d: "relating to the pleasant aspects of country life" },
  { w: "cacophony", d: "a harsh, jarring mixture of sounds" },
  { w: "cajole", d: "to persuade by flattery or gentle urging" },
  { w: "callous", d: "emotionally hardened and insensitive" },
  { w: "candid", d: "frank, open, and straightforward" },
  { w: "capitulate", d: "to surrender or give in after resistance" },
  { w: "capricious", d: "given to sudden, unpredictable changes of mind" },
  { w: "caustic", d: "sarcastically biting; able to burn" },
  { w: "censure", d: "to express strong official disapproval" },
  { w: "chagrin", d: "distress at being humiliated or disappointed" },
  { w: "charlatan", d: "a person who falsely claims special skill" },
  { w: "circuitous", d: "indirect and roundabout" },
  { w: "circumspect", d: "cautious and considering all circumstances" },
  { w: "clamor", d: "a loud outcry of protest or demand" },
  { w: "coalesce", d: "to come together and form one whole" },
  { w: "coerce", d: "to force someone to act by pressure or threats" },
  { w: "cogent", d: "clearly convincing and well reasoned" },
  { w: "complacent", d: "smugly self-satisfied and unworried" },
  { w: "conciliatory", d: "intended to soothe anger or restore goodwill" },
  { w: "condone", d: "to accept or overlook wrongdoing" },
  { w: "conflagration", d: "a large, destructive fire" },
  { w: "connoisseur", d: "an expert judge in matters of taste" },
  { w: "consensus", d: "general agreement among a group" },
  { w: "conspicuous", d: "easily noticed; attracting attention" },
  { w: "consternation", d: "sudden dismay that causes confusion" },
  { w: "contemptuous", d: "showing scornful disdain" },
  { w: "contentious", d: "likely to cause argument; quarrelsome" },
  { w: "contrite", d: "feeling sincere remorse for a wrong" },
  { w: "convoluted", d: "extremely complex and hard to follow" },
  { w: "copious", d: "abundant in quantity" },
  { w: "cordial", d: "warm and sincere in manner" },
  { w: "corroborate", d: "to confirm with supporting evidence" },
  { w: "credulous", d: "too ready to believe; easily fooled" },
  { w: "cryptic", d: "having a hidden or puzzling meaning" },
  { w: "culpable", d: "deserving blame" },
  { w: "cursory", d: "hasty and not thorough" },
  { w: "daunt", d: "to make someone feel intimidated or discouraged" },
  { w: "dearth", d: "a scarce supply; a shortage" },
  { w: "debilitate", d: "to weaken or drain of strength" },
  { w: "decorum", d: "proper, polite, and fitting behavior" },
  { w: "deference", d: "respectful yielding to another's wishes" },
  { w: "deleterious", d: "harmful, often in a subtle or gradual way" },
  { w: "delineate", d: "to describe or portray with precision" },
  { w: "demure", d: "reserved, modest, and quietly shy" },
  { w: "denounce", d: "to condemn publicly" },
  { w: "deplore", d: "to feel or express strong disapproval of" },
  { w: "deride", d: "to mock with contempt" },
  { w: "despot", d: "a ruler with absolute, often oppressive, power" },
  { w: "destitute", d: "extremely poor and lacking necessities" },
  { w: "deterrent", d: "something that discourages an action" },
  { w: "didactic", d: "intended to teach, sometimes overly so" },
  { w: "diffident", d: "lacking self-confidence; shy" },
  { w: "digress", d: "to wander away from the main subject" },
  { w: "diligent", d: "showing careful and persistent effort" },
  { w: "discern", d: "to perceive or recognize clearly" },
  { w: "discord", d: "lack of harmony; conflict" },
  { w: "discreet", d: "careful not to cause offense or leak secrets" },
  { w: "discrepancy", d: "a difference between things that should match" },
  { w: "disdain", d: "the feeling that something is unworthy of respect" },
  { w: "disparage", d: "to speak of in a slighting or belittling way" },
  { w: "disparate", d: "essentially different and distinct" },
  { w: "disseminate", d: "to spread widely, especially information" },
  { w: "dissent", d: "to differ in opinion from the majority" },
  { w: "dissonance", d: "a harsh clash or lack of agreement" },
  { w: "divergent", d: "moving apart from a common point" },
  { w: "dogmatic", d: "asserting opinions as if they were facts" },
  { w: "dubious", d: "doubtful or of questionable quality" },
  { w: "duplicity", d: "deceitful double-dealing" },
  { w: "egregious", d: "outstandingly bad" },
  { w: "eloquent", d: "fluent and persuasive in speech or writing" },
  { w: "elucidate", d: "to make something clear by explaining it" },
  { w: "elusive", d: "hard to find, catch, or pin down" },
  { w: "emaciated", d: "abnormally thin from hunger or illness" },
  { w: "embellish", d: "to add decorative or exaggerated details" },
  { w: "emulate", d: "to imitate in order to equal or surpass" },
  { w: "enervate", d: "to drain of energy or vitality" },
  { w: "engender", d: "to cause or give rise to" },
  { w: "enhance", d: "to improve the quality, value, or extent of" },
  { w: "enigma", d: "a puzzling person, thing, or situation" },
  { w: "ephemeral", d: "lasting for a very short time" },
  { w: "equanimity", d: "mental calmness under stress" },
  { w: "equivocal", d: "ambiguous; deliberately unclear" },
  { w: "erudite", d: "having or showing deep learning" },
  { w: "esoteric", d: "understood by only a small, specialized group" },
  { w: "eulogy", d: "a speech of praise, often for someone who has died" },
  { w: "euphemism", d: "a mild word used in place of a harsh one" },
  { w: "exacerbate", d: "to make a problem or feeling worse" },
  { w: "exalt", d: "to raise in rank, power, or high praise" },
  { w: "exemplary", d: "serving as a worthy model to follow" },
  { w: "exhaustive", d: "thorough and complete" },
  { w: "exonerate", d: "to clear someone of blame or fault" },
  { w: "expedient", d: "convenient and practical, though perhaps improper" },
  { w: "expedite", d: "to speed up the progress of" },
  { w: "explicit", d: "stated clearly and in detail" },
  { w: "extol", d: "to praise enthusiastically" },
  { w: "extraneous", d: "irrelevant or unrelated to the matter" },
  { w: "extricate", d: "to free from a constraint or difficulty" },
  { w: "exuberant", d: "filled with lively, unrestrained energy" },
  { w: "fallacious", d: "based on a mistaken or deceptive idea" },
  { w: "fastidious", d: "very attentive to accuracy and fine detail" },
  { w: "fathom", d: "to understand after deep thought" },
  { w: "feasible", d: "possible and practical to carry out" },
  { w: "fervent", d: "showing intense, passionate feeling" },
  { w: "fickle", d: "changing loyalties or interests frequently" },
  { w: "flagrant", d: "obviously and offensively wrong" },
  { w: "flippant", d: "not showing a serious or respectful attitude" },
  { w: "florid", d: "excessively ornate; flushed with color" },
  { w: "flout", d: "to openly disregard a rule or convention" },
  { w: "fortuitous", d: "happening by lucky chance" },
  { w: "fractious", d: "irritable and hard to control" },
  { w: "frugal", d: "sparing with money or resources" },
  { w: "furtive", d: "secretive and trying to avoid notice" },
  { w: "garrulous", d: "excessively talkative" },
  { w: "germane", d: "relevant to the matter at hand" },
  { w: "glib", d: "fluent but insincere and shallow" },
  { w: "grandiose", d: "impressive in a pompous or overly ambitious way" },
  { w: "gregarious", d: "sociable and fond of company" },
  { w: "guile", d: "sly or cunning intelligence" },
  { w: "hackneyed", d: "made stale by overuse" },
  { w: "haphazard", d: "lacking any obvious plan or order" },
  { w: "harangue", d: "a lengthy, aggressive speech" },
  { w: "haughty", d: "arrogantly superior in manner" },
  { w: "hedonist", d: "a person devoted to the pursuit of pleasure" },
  { w: "heresy", d: "a belief that goes against accepted doctrine" },
  { w: "homogeneous", d: "of uniform composition throughout" },
  { w: "hyperbole", d: "deliberate exaggeration not meant literally" },
  { w: "iconoclast", d: "a person who attacks cherished beliefs or institutions" },
  { w: "idiosyncrasy", d: "a distinctive personal habit or quirk" },
  { w: "ignominy", d: "public shame or disgrace" },
  { w: "imminent", d: "about to happen" },
  { w: "immutable", d: "unchanging over time" },
  { w: "impartial", d: "treating all sides fairly; unbiased" },
  { w: "impeccable", d: "without fault or error" },
  { w: "impede", d: "to delay or block the progress of" },
  { w: "imperious", d: "arrogantly commanding" },
  { w: "implicit", d: "implied though not plainly expressed" },
  { w: "impudent", d: "boldly disrespectful" },
  { w: "inadvertent", d: "not resulting from a deliberate plan" },
  { w: "incessant", d: "continuing without pause" },
  { w: "incisive", d: "intelligently analytical and sharply clear" },
  { w: "incongruous", d: "out of keeping with the surroundings" },
  { w: "incredulous", d: "unwilling or unable to believe something" },
  { w: "indifferent", d: "having no particular interest or concern" },
  { w: "indigenous", d: "originating naturally in a particular place" },
  { w: "indolent", d: "wanting to avoid activity or effort; lazy" },
  { w: "induce", d: "to persuade or bring about" },
  { w: "ineffable", d: "too great or extreme to be put into words" },
  { w: "infamy", d: "the state of being well known for a bad act" },
  { w: "inherent", d: "existing as a natural, essential quality" },
  { w: "inhibit", d: "to restrain, hinder, or hold back" },
  { w: "innocuous", d: "not harmful or offensive" },
  { w: "insipid", d: "lacking flavor, vigor, or interest" },
  { w: "insolent", d: "rude and arrogantly disrespectful" },
  { w: "instigate", d: "to provoke or stir up" },
  { w: "insular", d: "isolated and narrow-minded" },
  { w: "intrepid", d: "fearlessly adventurous" },
  { w: "inundate", d: "to overwhelm as if with a flood" },
  { w: "irascible", d: "easily angered" },
  { w: "jaded", d: "worn out and unenthusiastic from overexposure" },
  { w: "jargon", d: "specialized language of a particular group" },
  { w: "jocular", d: "fond of joking; playful" },
  { w: "judicious", d: "showing sound, careful judgment" },
  { w: "juxtapose", d: "to place side by side for contrast" },
  { w: "kindle", d: "to ignite or stir into activity" },
  { w: "labyrinth", d: "a complex maze of paths or ideas" },
  { w: "laconic", d: "using very few words" },
  { w: "lament", d: "to express grief, sorrow, or regret" },
  { w: "languid", d: "slow, relaxed, and lacking energy" },
  { w: "laud", d: "to praise highly" },
  { w: "lavish", d: "sumptuously rich, abundant, or generous" },
  { w: "lethargic", d: "sluggish and lacking energy" },
  { w: "levity", d: "humor or lightness, especially when seriousness is expected" },
  { w: "lucid", d: "clearly expressed and easy to understand" },
  { w: "lucrative", d: "producing a great deal of profit" },
  { w: "malevolent", d: "wishing harm to others" },
  { w: "malleable", d: "easily shaped, bent, or influenced" },
  { w: "meager", d: "lacking in quantity or richness" },
  { w: "melancholy", d: "a lingering, thoughtful sadness" },
  { w: "mercenary", d: "motivated chiefly by money" },
  { w: "meticulous", d: "showing extreme care about small details" },
  { w: "mitigate", d: "to make less severe, harsh, or painful" },
  { w: "morose", d: "sullen, gloomy, and ill-tempered" },
  { w: "mundane", d: "ordinary and lacking excitement" },
  { w: "munificent", d: "extremely generous" },
  { w: "nadir", d: "the lowest point" },
  { w: "naive", d: "lacking experience, wisdom, or sophistication" },
  { w: "nascent", d: "just coming into existence" },
  { w: "nefarious", d: "wicked or criminal" },
  { w: "negligible", d: "so small as to be unimportant" },
  { w: "nonchalant", d: "appearing calmly unconcerned" },
  { w: "nostalgia", d: "a sentimental longing for the past" },
  { w: "notorious", d: "famous for something bad" },
  { w: "novel", d: "new, original, and unusual" },
  { w: "novice", d: "a person new to a field or activity" },
  { w: "noxious", d: "harmful, poisonous, or morally corrupting" },
  { w: "nuance", d: "a subtle difference in meaning, feeling, or tone" },
  { w: "obfuscate", d: "to make unclear or unintelligible" },
  { w: "oblivious", d: "unaware of what is happening around one" },
  { w: "obscure", d: "not well known, or hard to understand" },
  { w: "obsolete", d: "no longer produced, used, or current" },
  { w: "obstinate", d: "stubbornly refusing to change course" },
  { w: "ominous", d: "suggesting that something bad is coming" },
  { w: "opaque", d: "not transparent; hard to understand" },
  { w: "opulent", d: "richly luxurious and abundant" },
  { w: "ostentatious", d: "showy in a way meant to impress" },
  { w: "palatable", d: "pleasant enough to accept or taste" },
  { w: "paltry", d: "small and of little value" },
  { w: "paradox", d: "a statement that seems contradictory but may be true" },
  { w: "paragon", d: "a perfect example of a quality" },
  { w: "partisan", d: "a strong, biased supporter of a side" },
  { w: "paucity", d: "a small or insufficient amount" },
  { w: "pedantic", d: "overly concerned with minor details of learning" },
  { w: "penchant", d: "a strong liking or habitual tendency" },
  { w: "pensive", d: "engaged in deep, often sad, thought" },
  { w: "perennial", d: "lasting a long time or recurring often" },
  { w: "perfidious", d: "deceitful and untrustworthy" },
  { w: "perfunctory", d: "done with minimal effort or interest" },
  { w: "pernicious", d: "having a gradually harmful effect" },
  { w: "perspicacious", d: "having keen insight and understanding" },
  { w: "pertinent", d: "directly relevant to the matter at hand" },
  { w: "pervade", d: "to spread through every part of" },
  { w: "petulant", d: "childishly sulky or bad-tempered" },
  { w: "philanthropy", d: "the effort to promote others' welfare, especially by gifts" },
  { w: "pious", d: "devoutly religious, or making a show of virtue" },
  { w: "pithy", d: "concise and forcefully expressive" },
  { w: "placate", d: "to make someone less angry or hostile" },
  { w: "platitude", d: "a remark that is overused and unoriginal" },
  { w: "plausible", d: "seeming reasonable or probable" },
  { w: "poignant", d: "evoking a keen sense of sadness or regret" },
  { w: "pompous", d: "affectedly grand and self-important" },
  { w: "pragmatic", d: "dealing with things in a practical, realistic way" },
  { w: "precarious", d: "not securely held; dangerously uncertain" },
  { w: "precedent", d: "an earlier case used as an example later" },
  { w: "precipitate", d: "to cause to happen suddenly; acting rashly" },
  { w: "preclude", d: "to make impossible in advance" },
  { w: "precocious", d: "having developed abilities unusually early" },
  { w: "pretentious", d: "trying to impress by affecting greater importance" },
  { w: "prevalent", d: "widespread in a particular area or time" },
  { w: "pristine", d: "in original, unspoiled condition" },
  { w: "prodigal", d: "wastefully extravagant" },
  { w: "prodigious", d: "remarkably great in size, extent, or degree" },
  { w: "profound", d: "very great, intense, or intellectually deep" },
  { w: "prolific", d: "producing many works, results, or offspring" },
  { w: "propensity", d: "a natural tendency to behave in a certain way" },
  { w: "prosaic", d: "dull, ordinary, and lacking imagination" },
  { w: "provincial", d: "narrow-minded; limited to a small locality" },
  { w: "prudent", d: "acting with care and thought for the future" },
  { w: "pugnacious", d: "eager to argue or fight" },
  { w: "pungent", d: "having a sharply strong taste or smell" },
  { w: "quandary", d: "a state of uncertainty over what to do" },
  { w: "querulous", d: "complaining in a whining, peevish way" },
  { w: "quixotic", d: "exceedingly idealistic and unrealistic" },
  { w: "rancor", d: "bitter, long-lasting resentment" },
  { w: "rapport", d: "a close, harmonious relationship" },
  { w: "raucous", d: "disturbingly loud and harsh" },
  { w: "ravenous", d: "extremely hungry; greedy for something" },
  { w: "recalcitrant", d: "stubbornly uncooperative" },
  { w: "recant", d: "to withdraw a former statement or belief" },
  { w: "recluse", d: "a person who lives a withdrawn, solitary life" },
  { w: "rectify", d: "to put right; to correct" },
  { w: "relegate", d: "to assign to a lower or less important position" },
  { w: "relinquish", d: "to give up or let go of" },
  { w: "remorse", d: "deep regret for a wrong committed" },
  { w: "remunerate", d: "to pay someone for work or a service" },
  { w: "reprehensible", d: "deserving strong condemnation" },
  { w: "reprimand", d: "a formal expression of disapproval" },
  { w: "reproach", d: "to express disappointment or blame" },
  { w: "repudiate", d: "to reject or refuse to be associated with" },
  { w: "resilient", d: "able to recover quickly from difficulty" },
  { w: "resolute", d: "admirably determined and unwavering" },
  { w: "respite", d: "a short period of rest or relief" },
  { w: "reticent", d: "not revealing thoughts or feelings readily" },
  { w: "revere", d: "to regard with deep respect and awe" },
  { w: "rhetoric", d: "the art of persuasive speaking or writing" },
  { w: "rigor", d: "strictness, severity, or demanding precision" },
  { w: "robust", d: "strong, healthy, and vigorous" },
  { w: "rudimentary", d: "involving only the most basic principles" },
  { w: "sage", d: "a profoundly wise person, or wisely judicious" },
  { w: "sanctimonious", d: "making a show of being morally superior" },
  { w: "sanguine", d: "cheerfully optimistic" },
  { w: "scanty", d: "small or insufficient in amount" },
  { w: "scrupulous", d: "careful to be honest, exact, and thorough" },
  { w: "scrutinize", d: "to examine closely and thoroughly" },
  { w: "secular", d: "not connected with religion" },
  { w: "sedulous", d: "showing dedicated, persistent diligence" },
  { w: "serene", d: "calm, peaceful, and untroubled" },
  { w: "servile", d: "excessively eager to please or obey" },
  { w: "skeptical", d: "not easily convinced; having doubts" },
  { w: "solemn", d: "formal, dignified, and serious" },
  { w: "solicitous", d: "showing anxious concern for someone's welfare" },
  { w: "somber", d: "dark or dull in tone; gloomy" },
  { w: "soporific", d: "tending to induce drowsiness or sleep" },
  { w: "sparse", d: "thinly scattered; in short supply" },
  { w: "spurious", d: "not genuine; false" },
  { w: "squalid", d: "extremely dirty, neglected, and unpleasant" },
  { w: "stagnant", d: "showing no activity, flow, or development" },
  { w: "steadfast", d: "firmly loyal and unwavering" },
  { w: "stoic", d: "enduring pain or hardship without complaint" },
  { w: "strident", d: "loud, harsh, and grating" },
  { w: "stupefy", d: "to astonish or make unable to think clearly" },
  { w: "submissive", d: "ready to yield to the authority of others" },
  { w: "substantiate", d: "to provide evidence that supports a claim" },
  { w: "subtle", d: "so delicate or precise as to be hard to notice" },
  { w: "succinct", d: "briefly and clearly expressed" },
  { w: "superfluous", d: "more than is needed; extra and unnecessary" },
  { w: "surreptitious", d: "kept secret because it would not be approved" },
  { w: "sycophant", d: "a person who flatters the powerful to gain favor" },
  { w: "tacit", d: "understood or implied without being stated" },
  { w: "taciturn", d: "reserved in speech; habitually quiet" },
  { w: "tangential", d: "only slightly related to the main matter" },
  { w: "tenacious", d: "holding firmly; persistent" },
  { w: "tenuous", d: "very weak, slight, or insubstantial" },
  { w: "terse", d: "sparing in words; abruptly brief" },
  { w: "tirade", d: "a long, angry speech of criticism" },
  { w: "torpid", d: "mentally or physically inactive; sluggish" },
  { w: "tractable", d: "easy to control, teach, or influence" },
  { w: "transient", d: "lasting only a short time; passing" },
  { w: "trepidation", d: "a feeling of fearful anxiety" },
  { w: "trite", d: "overused and therefore uninteresting" },
  { w: "tumultuous", d: "loud, disorderly, and full of upheaval" },
  { w: "ubiquitous", d: "present, appearing, or found everywhere" },
  { w: "undermine", d: "to weaken gradually or secretly" },
  { w: "underscore", d: "to emphasize or draw attention to" },
  { w: "unprecedented", d: "never done or known before" },
  { w: "urbane", d: "suave, courteous, and refined in manner" },
  { w: "usurp", d: "to seize a position of power illegally or by force" },
  { w: "vacillate", d: "to waver between options or opinions" },
  { w: "vapid", d: "offering nothing stimulating; dull" },
  { w: "vehement", d: "showing strong, forceful feeling" },
  { w: "venerate", d: "to regard with great respect" },
  { w: "verbose", d: "using more words than are needed" },
  { w: "vex", d: "to annoy, worry, or irritate" },
  { w: "viable", d: "capable of working successfully" },
  { w: "vicarious", d: "experienced through the feelings or actions of another" },
  { w: "vigilant", d: "keeping careful watch for possible danger" },
  { w: "vilify", d: "to speak about in an abusively disparaging way" },
  { w: "vindicate", d: "to clear of blame or justify with evidence" },
  { w: "virtuoso", d: "a person highly skilled in an art, especially music" },
  { w: "virulent", d: "extremely severe, harmful, or bitterly hostile" },
  { w: "volatile", d: "liable to change rapidly and unpredictably" },
  { w: "voluminous", d: "occupying much space; lengthy" },
  { w: "voracious", d: "wanting or devouring great quantities" },
  { w: "vulnerable", d: "exposed to the possibility of harm" },
  { w: "wane", d: "to decrease in vigor, power, or extent" },
  { w: "wary", d: "feeling or showing caution about possible danger" },
  { w: "whimsical", d: "playfully quaint, fanciful, or unpredictable" },
  { w: "wily", d: "skilled at gaining an advantage, especially by cunning" },
  { w: "wistful", d: "having a feeling of vague or regretful longing" },
  { w: "zealot", d: "a person fanatical in pursuit of an ideal or cause" },
  { w: "zenith", d: "the highest point; the peak" },
  { w: "chastise", d: "to scold or punish severely" },
  { w: "panacea", d: "a supposed cure for all difficulties" },
  { w: "obdurate", d: "stubbornly refusing to change one's mind" },
  { w: "redolent", d: "strongly suggestive of; richly fragrant" },
  { w: "umbrage", d: "offense or annoyance" },
  { w: "winsome", d: "attractive in a fresh, innocent way" },
  { w: "inveterate", d: "having a long-established habit that is hard to change" },
  { w: "maudlin", d: "tearfully or weakly sentimental" },
  { w: "forestall", d: "to prevent by taking action ahead of time" },
  { w: "evanescent", d: "quickly fading from sight, memory, or existence" },
];
